name: Pull Request Validation

concurrency:
  group: pull_request_${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  pr-review:
    name: Pull request validation

    if: github.event_name != 'pull_request' || !github.event.pull_request.draft

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - name: Begin CI...
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Validate pull request
        run: node .github/scripts/pr-validation.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
