name: Lint Code Base

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      validate_all_codebase:
        description: 'Validate all code base'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event.inputs.validate_all_codebase || false }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TYPESCRIPT_STANDARD: false
          LINTER_RULES_PATH: .
          MARKDOWN_CONFIG_FILE: .markdownlint.json
